// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 10.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace Pripev.TextTemplates.Email
{
    using System;
    
    
    #line 1 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public partial class OrdersNotify : OrdersNotifyBase
    {
        public virtual string TransformText()
        {
            this.Write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0 Transitional//EN\">\r\n<html>\r\n    <head" +
                    ">\r\n        <meta http-equiv=\"Content-Type\" content=\"text/html; charset=windows-1" +
                    "251\" />\r\n\t\t<title>");
            
            #line 5 "C:\Projects\Pripev\Code\TextTemplates\Email\EmailHeader.t4"
            this.Write(this.ToStringHelper.ToStringWithCulture(HtmlTitle));
            
            #line default
            #line hidden
            this.Write("</title>\r\n\t\t<style type=\"text/css\">\r\n\t\t\t");
            this.Write(@"body {margin:0; padding:0; color:#222222;background: #F4F0EE; font:normal 10px Verdana,Arial,Helvetica,sans-serif; scrollbar-base-color:#F4F0EE;text-align: left;}
a, a:visited, a:link {color:#222222}
a:hover {color:#FCBD03;}
hr {height:1px; color:#BE9175;}
table.data {border-left:1px solid #BE9175; border-right:1px solid #BE9175; border-bottom:1px solid #BE9175; background:#FFFFFC; font:10px Verdana; padding:0;border-spacing:0;}
table.data th {padding:0 5px; font:11px Verdana; color:#444444; background-color:#FDF6D1; font-weight:bold; text-align:left; height:20px;border-bottom: 1px solid #FACDB1;border-spacing:0;}
table.data td {padding:0 2px; height:18px; color:#222222; text-align:left; border-left:1px dashed #FACDB1; white-space:nowrap;}
table.data td a {white-space:nowrap;}
table.data td.first { border-left: none;}
");
            this.Write("\r\n\t\t</style>\r\n    </head>\r\n    <body>");
            this.Write("\r\n\t\t<img src=\'http://pripev64/Images/LogoOrders.gif\' />\r\n\t\t<br />\r\n\t\t<table class" +
                    "=\'data\'>\r\n\t\t\t<tr><th>Исполнитель</th><th>Альбом</th><th>Композиция</th></tr>\r\n\t\t" +
                    "\t");
            
            #line 7 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
 foreach( var o in Orders) { 
            
            #line default
            #line hidden
            this.Write("\t\t\t\t<tr><td class=\'first\'>");
            
            #line 8 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Artist));
            
            #line default
            #line hidden
            this.Write("</td><td>");
            
            #line 8 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Album));
            
            #line default
            #line hidden
            this.Write("</td><td><a href=\'");
            
            #line 8 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Url));
            
            #line default
            #line hidden
            this.Write("\'>");
            
            #line 8 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(o.Song));
            
            #line default
            #line hidden
            this.Write("</a></td></tr>\r\n\t\t\t");
            
            #line 9 "C:\Projects\Pripev\Code\TextTemplates\Email\OrdersNotify.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\t\t</table>\r\n");
            this.Write("\t</body>\r\n</html>");
            this.Write("\r\n");
            return this.GenerationEnvironment.ToString();
        }
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "10.0.0.0")]
    public class OrdersNotifyBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
