ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_ADDED]  DEFAULT (getdate()) FOR [ADDED]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_ALBUMS]  DEFAULT ((0)) FOR [ALBUMS]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_CD]  DEFAULT ((0)) FOR [CD]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_SONGS]  DEFAULT ((0)) FOR [SONGS]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_TEXTS]  DEFAULT ((0)) FOR [TEXTS]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_CHORDS]  DEFAULT ((0)) FOR [CHORDS]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_MP3]  DEFAULT ((0)) FOR [MP3]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_MP3ONLINE]  DEFAULT ((0)) FOR [MP3ONLINE]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_MID]  DEFAULT ((0)) FOR [MID]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_KAR]  DEFAULT ((0)) FOR [KAR]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_MOV]  DEFAULT ((0)) FOR [MOV]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_ActiveFlag]  DEFAULT ('Y') FOR [ListFlag]
GO

ALTER TABLE [dbo].[ARTISTS] ADD  CONSTRAINT [DF_ARTISTS_DetailsFlag]  DEFAULT ('Y') FOR [DetailsFlag]
GO
